# test=error control reaches end of function
4 main()
{
}
